# Generated by Django 6.0.4 on 2026-04-08 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitorEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visitor_name", models.CharField(max_length=100)),
                ("visitor_phone", models.CharField(max_length=15)),
                (
                    "relation",
                    models.CharField(
                        choices=[
                            ("parent", "Parent"),
                            ("guardian", "Guardian"),
                            ("sibling", "Sibling"),
                            ("friend", "Friend"),
                            ("relative", "Relative"),
                            ("other", "Other"),
                        ],
                        default="parent",
                        max_length=15,
                    ),
                ),
                ("purpose", models.CharField(max_length=200)),
                ("check_in", models.DateTimeField(auto_now_add=True)),
                ("check_out", models.DateTimeField(blank=True, null=True)),
                (
                    "id_proof",
                    models.CharField(
                        blank=True, help_text="ID proof number", max_length=100
                    ),
                ),
                (
                    "logged_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logged_visitors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitor_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Visitor Entries",
                "ordering": ["-check_in"],
            },
        ),
    ]
